export default {
  STATUS_500: 500,
  STATUS_400: 400,
  STATUS_401: 401,
  STATUS_403: 403,
  STATUS_404: 404,
  STATUS_419: 419,
  STATUS_422: 422,
  ERROR_NOT_FOUND: "No se ha encontrado lo que solicitas!",
  ERROR_AUTH_TOKEN: "Autenticación invalido!",
  ERROR_AUTH_PUBLIC_KEY: "No tienes permisos para acceder al recurso",
  ERROR_NOT_VALIDATE: "Acción no válida!",
  REGISTER: "user registered",
  LOGIN: "login",
  ERROR_USER: "user no registered",
  INACTIVE_USER: "Inactive user",
  USERNAME: "Nombre de usuario ya se encuentra registrado",
  EMAIL: "Email ya se encuentra registrado",
  FORMAT_IMAGE_INVALID: "The format image is invalid",
  NO_AUTHORIZED: "No authorized",
};
